# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
  	ensure_git_status_clean
	  increment_build_number(xcodeproj: "Rondo-iOS.xcodeproj")
	  commit_version_bump(xcodeproj: "Rondo-iOS.xcodeproj")
	  push_to_git_remote
    build_app(workspace: "Rondo-iOS.xcworkspace", scheme: "Rondo-iOS")
    # upload_to_testflight
    crashlytics(api_token: "f5fbda44a9b5e82066a5b742bf34f8b260e1ebe9", build_secret: "6b3ac6876b163995797a9440cde4ae40e1db0f7d8c0c4747b753913e100fe291")
  end
end
